### ISSUE TITLE
Shortcut?

### ISSUE THREAD

**Issue by probablykasper** [viktorstrate/color-picker-plus#1]
I'm not sure if this is possible at all, but could there be a way to copy the color code using a shortcut?

**Comment by viktorstrate** [comment]
This should be possible, I will look further into that :)

**Comment by viktorstrate** [comment]
I've added some default shortcuts to the menu items in [Release 1.2](https://github.com/viktorstrate/color-picker-plus/releases/tag/v1.2)

**Comment by kasper9n** [comment]
Awesome stuff, thank you so much!
