### ISSUE TITLE
Doesn't work with Mac OS Mojave

### ISSUE THREAD

**Issue by karamfd** [viktorstrate/color-picker-plus#10]
The app works with High Sierra, but ever since I upgraded to Mojave, the app does not work. I can only see the default colour pickers that are preinstalled in Mac OS.

**Comment by viktorstrate** [comment]
I know about the problem and I have been trying to solve it for a while, but without luck.
I cannot find any updated documentation on the topic.

I have only found this open-source project [DemoColorPicker](https://github.com/macoscope/DemoColorPicker), but it doesn't work either.
It's the same for other old color pickers.

I found [Skala Color Picker](https://bjango.com/mac/skalacolor/), which is working on Mojave.
Unfortunately, it isn't open-source, so I can't see how they did it.

If anyone knows where to find documentation, or a working open-source example, please reply.

--------

The console prints the following, when opening the color panel.

```
error 15:01:21.005496 +0100 LegacyExternalColorPickerService flock failed to lock maps file: errno = 35
default 15:01:21.032292 +0100 LegacyExternalColorPickerService Error loading /Users/viktorstrate/Library/ColorPickers/Color Picker Plus.colorPicker/Contents/MacOS/Color Picker Plus: dlopen(/Users/viktorstrate/Library/ColorPickers/Color Picker Plus.colorPicker/Contents/MacOS/Color Picker Plus, 0x0109): dependent dylib '@rpath/libswiftAppKit.dylib' not found for '/Users/viktorstrate/Library/ColorPickers/Color Picker Plus.colorPicker/Contents/MacOS/Color Picker Plus'
error 15:01:21.032998 +0100 applet Error occurred during -advanceToRunPhaseIfNeeded: for color picker at '': Error Domain=com.apple.ViewBridge Code=16 UserInfo={com.apple.ViewBridge.error.hint=advance to run phase, com.apple.ViewBridge.error.description=NSViewBridgeServiceInvalidError}
error 15:01:21.033215 +0100 applet Remote color picker at was invalidated and removed
```

Under Build Settings for the target, `Always Embed Swift Standard Libraries` is enabled.
Which should solve the `dependent dylib '@rpath/libswiftAppKit.dylib' not found` part, but obviosly doesn't.

**Comment by mmeeaatt** [comment]
Hi 

Any news on this issue?

I really want to use your app on Mojave...

**Comment by viktorstrate** [comment]
@mmeeaatt, @karamfd 
I have simply recompiled the binaries it now runs on Mojave. See the [latest release](https://github.com/viktorstrate/color-picker-plus/releases/tag/v1.3.1)
I have tested it successfully on macOS version 10.14.4

Will someone please test the new release, and confirm that it is working, so this issue can be closed?

**Comment by mmeeaatt** [comment]
@viktorstrate 
1.3.1 work good on Mojave 10.14.4.

Thanks a lot!
