### ISSUE TITLE
Scrolling inside text fields

### ISSUE THREAD

**Issue by probablykasper** [viktorstrate/color-picker-plus#4]
A little thing that would hopefully make the color picker more useful to use.

Ability to scroll inside text fields to increase/decrease values. Maybe even on the sliders?

**Comment by viktorstrate** [comment]
I think this is a great idea. I am thinking about making the corresponding labels for the text-fields "dragable", and making the up/down arrow keys change the values more precisely

**Comment by kasper9n** [comment]
How would the dragging work?

**Comment by viktorstrate** [comment]
If you click and hold on one of the labels like "Hue:" or "Saturation:", and then drag left/right, that field should change.

**Comment by viktorstrate** [comment]
This has been implemented in commit f3ec307
