### ISSUE TITLE
Weird text field alignment

### ISSUE THREAD

**Issue by probablykasper** [viktorstrate/color-picker-plus#6]
The alignment of the text fields is kinda weird. I think it would be better to have a layout like this. Might take up more space vertically, but I believe it should fit (Photoshop's color picker, for instance, has smaller fonts and less margin between the text fields).
```
Hue:              [     ] °
Saturation:       [     ] %
Brightness:       [     ] %
Red:              [     ]
Green:            [     ]
Blue:             [     ]
Alpha             [12345] %

# [12345678]    [Copy   ]
```

**Comment by viktorstrate** [comment]
I think I like the way the fields are layed out currently.
But I will move the alpha field a little to the right, to line up with the copy drop-down.
