### ISSUE TITLE
Remove one of the opacity sliders?

### ISSUE THREAD

**Issue by probablykasper** [viktorstrate/color-picker-plus#9]
I'm mostly wondering why there are two opacity sliders. They do the same thing, and the larger one doesn't even seem to offer much more precision (at least for me?)

**Comment by kasper9n** [comment]
Sorry to bother you with all the issues, just thought I'd give my suggestions to it <3

I gotta say though, I absolutely love this color picker. Was looking around everywhere for something good.

**Comment by viktorstrate** [comment]
I don't think it is possible to remove the 'native' slider - the one at the bottom. And somtimes that one doesn't show up. So I still think it is good to have.


<img width="594" alt="screen shot 2018-06-25 at 01 05 21" src="https://user-images.githubusercontent.com/4233458/41824641-dad6a470-7813-11e8-9dd2-7e5c381f071e.png">

**Comment by kasper9n** [comment]
Oh, I see. Didn't realize it shows up in all of the tabs. Any idea why it doesn't show up for you sometimes?

**Comment by viktorstrate** [comment]
I guess if you pick a color for somthing that doesn't support transparency, is does not show up. But I think it can be nice to have either way, at least for copying the color values.

**Comment by viktorstrate** [comment]
Im closing this for now. If anyone still thinks, this is a problem, please feel free to comment, and I will reopen the issue.
